# Generated by Django 2.2.5 on 2020-03-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=50)),
                ('clave', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=13)),
                ('direccion', models.TextField(default='sin direccion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=75, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automatica', 'Automatica')], default='Manual', max_length=35)),
                ('nro_puertas', models.IntegerField(max_length=10)),
                ('nro_asientos', models.IntegerField(max_length=10)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('aire_acondicionado', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=15)),
                ('imagen', models.ImageField(null=True, upload_to='portadas')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioA',
            fields=[
                ('horarioA_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recogida', models.DateField(null=True)),
                ('dias', models.IntegerField(max_length=10)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('precio_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('alquiler_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField(null=True)),
                ('hora_recogida', models.TimeField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.HorarioA')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Persona')),
            ],
        ),
    ]
