# Generated by Django 2.2.5 on 2020-03-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=75, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('transmision', models.CharField(choices=[('Manual', 'Manual'), ('Automatica', 'Automatica')], default='Manual', max_length=35)),
                ('nro_puertas', models.IntegerField(max_length=10)),
                ('nro_asientos', models.IntegerField(max_length=10)),
                ('tipo_vehiculo', models.IntegerField(max_length=50)),
                ('aire_acondicionado', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=15)),
                ('imagen', models.ImageField(null=True, upload_to='portadas')),
            ],
        ),
    ]
