# Generated by Django 2.2.5 on 2020-03-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='fecha_alquiler',
        ),
    ]
