# Generated by Django 2.2.5 on 2020-03-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_auto_20200320_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioA',
            fields=[
                ('horarioA_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recogida', models.DateField(null=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('hora_recogida', models.TimeField()),
                ('precio_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
